stages:
  - publish

.kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: publish
  variables:
    SUFFIX: ""
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${DOCKER_HUB_REGISTRY_USER}:${DOCKER_HUB_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context .
      --dockerfile $(echo "$(echo ${DOCKER_HUB_COMMIT_TAG} | cut -d - -f 1)/$(echo ${DOCKER_HUB_COMMIT_TAG} | cut -d - -f 3)/$(echo ${DOCKER_HUB_COMMIT_TAG} | cut -d - -f 2)/Dockerfile${SUFFIX}")
      --destination $DOCKER_HUB_REGISTRY_IMAGE:$DOCKER_HUB_COMMIT_TAG
      --force
  rules:
    - if: $CI_COMMIT_TAG

DHub:Prod:
  extends:
    - .kaniko
  variables:
    DOCKER_HUB_COMMIT_TAG: ${CI_COMMIT_TAG}


DHub:Dev:
  extends:
    - .kaniko
  variables:
    SUFFIX: ".dev"
    DOCKER_HUB_COMMIT_TAG: ${CI_COMMIT_TAG}-dev
